import polars as pl
from typing import TypeVar

DataFrameType = TypeVar('DataFrameType', pl.LazyFrame, pl.DataFrame)

def downcast_strings(data_frame: DataFrameType) -> DataFrameType: ...
def test_downcast_strings_eager() -> None: ...
def test_downcast_strings_lazy() -> None: ...
